version: '3.8'

services:
  web-test:
    build:
      context: .
      dockerfile: docker/local/Dockerfile
    entrypoint: docker/local/entrypoint.sh
    volumes:
      - .:/usr/src/app
    env_file: docker-compose.test.env
    ports:
      - "9881:9000"
    networks:
      - market-access-api_webnet
    command: ./manage.py runserver 0:9000
  chrome:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    networks:
      - market-access-api_webnet
    extra_hosts:
      - "market-access-api-dev.london.cloudapps.digital:35.178.70.89"
      - "market-access-pyfe-dev.london.cloudapps.digital:35.178.70.89"
      - "market-access-api-uat.london.cloudapps.digital:35.178.70.89"
      - "market-access-pyfe-uat.london.cloudapps.digital:35.178.70.89"

networks:
  market-access-api_webnet:
    external: true
